import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <script
          src={`${process.env.NEXT_PUBLIC_API_URL}/Scripts/jquery-3.4.1.min.js`}
        ></script>
        {/* <!--Reference the SignalR library. --> */}
        <script
          src={`${process.env.NEXT_PUBLIC_API_URL}/Scripts/jquery.signalR-2.2.2.min.js`}
        />
        {/* <!--Reference the autoGenerated SignalR hub script. --> */}
        <script src={`${process.env.NEXT_PUBLIC_API_URL}/signalr/hubs`} />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
