import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <script src="https://nucares.top/Scripts/jquery-3.4.1.min.js"></script>
        {/* <!--Reference the SignalR library. --> */}
        <script src="https://nucares.top/Scripts/jquery.signalR-2.2.2.min.js" />
        {/* <!--Reference the autoGenerated SignalR hub script. --> */}
        <script src="https://nucares.top/signalr/hubs" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
